services:
  db:
    image: postgres:17
    container_name: todo_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    build: ./backend
    container_name: todo_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
    environment:
      ACCESS_TOKEN_EXPIRY: ${ACCESS_TOKEN_EXPIRY}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      SECRET_KEY: ${SECRET_KEY}
      DB_URL: ${DB_URL}
      TEST_DB_URL: ${TEST_DB_URL}

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
